version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: surveyjs-widgets
    versions:
    - 1.8.28
    - 1.8.29
    - 1.8.30
    - 1.8.31
    - 1.8.32
    - 1.8.33
    - 1.8.34
    - 1.8.35
    - 1.8.36
    - 1.8.37
    - 1.8.38
    - 1.8.39
    - 1.8.40
    - 1.8.41
    - 1.8.42
    - 1.8.43
    - 1.8.44
  - dependency-name: survey-vue
    versions:
    - 1.8.28
    - 1.8.29
    - 1.8.30
    - 1.8.31
    - 1.8.32
    - 1.8.33
    - 1.8.34
    - 1.8.35
    - 1.8.36
    - 1.8.37
    - 1.8.38
    - 1.8.39
    - 1.8.40
    - 1.8.41
    - 1.8.42
    - 1.8.43
    - 1.8.44
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: chromedriver
    versions:
    - 88.0.0
    - 89.0.0
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.5.0
    - 7.6.0
    - 7.7.0
    - 7.8.0
  - dependency-name: auth0-js
    versions:
    - 9.14.3
    - 9.15.0
  - dependency-name: "@vue/cli-plugin-e2e-nightwatch"
    versions:
    - 4.5.11
  - dependency-name: "@vue/cli-plugin-babel"
    versions:
    - 4.5.11
  - dependency-name: "@vue/babel-preset-app"
    versions:
    - 4.5.11
